/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.NotaFiscal;
import model.Venda;

/**
 *
 * @author paulo
 */
public class TelaDeResumo extends javax.swing.JFrame {
    private NotaFiscal nota;
    
    public TelaDeResumo(NotaFiscal n) {
	initComponents();
	nota = n;
	jtaresumo.setText(nota.gerarNota());
	setPrecoTotal(nota.getVenda().getPrecototal());
	setValorPago(nota.getVenda().getDinheiro());
	setTroco(nota.getVenda().getDinheiro() - nota.getVenda().getPrecototal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jltotal = new javax.swing.JLabel();
        jlpago = new javax.swing.JLabel();
        jltroco = new javax.swing.JLabel();
        jlvt = new javax.swing.JLabel();
        jlvp = new javax.swing.JLabel();
        jlt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaresumo = new javax.swing.JTextArea();
        jbconcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finalização");

        jltotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jltotal.setText("Valor Total");

        jlpago.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlpago.setText("Valor Pago");

        jltroco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jltroco.setText("Troco");

        jlvt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlvt.setText("R$ 0.00");

        jlvp.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlvp.setText("R$ 0.00");

        jlt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlt.setText("R$ 0.00");

        jtaresumo.setEditable(false);
        jtaresumo.setColumns(20);
        jtaresumo.setRows(5);
        jScrollPane1.setViewportView(jtaresumo);

        jbconcluir.setText("Concluir");
        jbconcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jltotal)
                            .addComponent(jlvt)
                            .addComponent(jlpago)
                            .addComponent(jlvp)
                            .addComponent(jltroco)
                            .addComponent(jlt))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbconcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(jltotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlvt)
                        .addGap(18, 18, 18)
                        .addComponent(jlpago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlvp)
                        .addGap(18, 18, 18)
                        .addComponent(jltroco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlt)
                        .addGap(18, 18, 18)
                        .addComponent(jbconcluir)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbconcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconcluirActionPerformed
        dispose();
    }//GEN-LAST:event_jbconcluirActionPerformed

    public void setPrecoTotal(double preco){
	jlvt.setText("R$: " + preco);
    }
    
    public void setValorPago(double preco){
	jlvp.setText("R$: " + preco);
    }
    
    public void setTroco(double preco){
	jlt.setText("R$: " + preco);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbconcluir;
    private javax.swing.JLabel jlpago;
    private javax.swing.JLabel jlt;
    private javax.swing.JLabel jltotal;
    private javax.swing.JLabel jltroco;
    private javax.swing.JLabel jlvp;
    private javax.swing.JLabel jlvt;
    private javax.swing.JTextArea jtaresumo;
    // End of variables declaration//GEN-END:variables
}
