/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDAO;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import model.Item;
import model.NotaFiscal;
import model.Venda;

public class TelaDeVenda extends javax.swing.JFrame {
    private VendaTableModel vtm = new VendaTableModel();
    private Item novoitem;
    private Venda venda = new Venda();
    
    public TelaDeVenda() {
        initComponents();
	jftfcodigo.setFocusTraversalKeysEnabled(false);
	novoitem = new Item();
	vtm.setVenda(venda);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jttotal = new javax.swing.JTextField();
        jftfcodigo = new javax.swing.JFormattedTextField();
        jftfquantidade = new javax.swing.JFormattedTextField();
        jtfvalorunitario = new javax.swing.JTextField();
        jtfsubtotal = new javax.swing.JTextField();
        jbpesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlcliente = new javax.swing.JLabel();
        jbselecionarcliente = new javax.swing.JButton();
        jlclienteselecionado = new javax.swing.JLabel();
        jpnomeproduto = new javax.swing.JPanel();
        jlitematual = new javax.swing.JLabel();
        jbfinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlistadecompras = new javax.swing.JTable();
        jbremover = new javax.swing.JButton();
        jblimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Venda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitário");

        jLabel4.setText("Sub Total");

        jLabel5.setText("Total a Pagar");

        jttotal.setEditable(false);
        jttotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jftfcodigo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftfcodigoKeyTyped(evt);
            }
        });

        jftfquantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfquantidade.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftfquantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftfquantidadeKeyPressed(evt);
            }
        });

        jtfvalorunitario.setEditable(false);
        jtfvalorunitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtfsubtotal.setEditable(false);
        jtfsubtotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtfsubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pesquisar.png"))); // NOI18N
        jbpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfsubtotal)
                    .addComponent(jttotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jftfquantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfvalorunitario))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftfcodigo))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfvalorunitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jlcliente.setText("Cliente:");

        jbselecionarcliente.setText("Selecionar");
        jbselecionarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbselecionarclienteActionPerformed(evt);
            }
        });

        jlclienteselecionado.setText("<Nenhum cliente selecionado>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlclienteselecionado)
                .addGap(459, 459, 459)
                .addComponent(jbselecionarcliente)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbselecionarcliente)
                    .addComponent(jlcliente)
                    .addComponent(jlclienteselecionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnomeproduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlitematual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlitematual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnomeprodutoLayout = new javax.swing.GroupLayout(jpnomeproduto);
        jpnomeproduto.setLayout(jpnomeprodutoLayout);
        jpnomeprodutoLayout.setHorizontalGroup(
            jpnomeprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnomeprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlitematual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnomeprodutoLayout.setVerticalGroup(
            jpnomeprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnomeprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlitematual, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbfinalizar.setText("Finalizar Compra");
        jbfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfinalizarActionPerformed(evt);
            }
        });

        jtlistadecompras.setModel(vtm);
        jtlistadecompras.getTableHeader().setReorderingAllowed(false);
        jtlistadecompras.setAutoResizeMode(jtlistadecompras.AUTO_RESIZE_OFF);
        for(int i = 0; i < jtlistadecompras.getColumnCount(); i++){
            jtlistadecompras.getColumnModel().getColumn(i).setResizable(false);
        }
        jtlistadecompras.getColumnModel().getColumn(0).setPreferredWidth(35);
        jtlistadecompras.getColumnModel().getColumn(1).setPreferredWidth(81);
        jtlistadecompras.getColumnModel().getColumn(2).setPreferredWidth(466);
        jtlistadecompras.getColumnModel().getColumn(3).setPreferredWidth(60);
        jtlistadecompras.getColumnModel().getColumn(4).setPreferredWidth(82);
        jtlistadecompras.getColumnModel().getColumn(5).setPreferredWidth(82);

        jScrollPane1.setViewportView(jtlistadecompras);

        jbremover.setText("Remover Item");
        jbremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbremoverActionPerformed(evt);
            }
        });

        jblimpar.setText("Limpar Lista");
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbremover, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnomeproduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbfinalizar)
                    .addComponent(jblimpar)
                    .addComponent(jbremover))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbremoverActionPerformed
        vtm.getVenda().removerItem(jtlistadecompras.getSelectedRow());
	vtm.fireTableDataChanged();
    }//GEN-LAST:event_jbremoverActionPerformed

    private void jftfcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftfcodigoKeyTyped
	int key = evt.getKeyChar();
	if(key == KeyEvent.VK_ENTER){
	    if(jftfcodigo.getText().isEmpty()){
		jbpesquisar.doClick();
	    }else{
		ProdutoDAO p = new ProdutoDAO();
		try{
		    novoitem.setProduto(p.recuperar(Integer.parseInt(jftfcodigo.getText())));
		    DecimalFormat df = new DecimalFormat("#.00");
		    jtfvalorunitario.setText("R$ " + df.format(novoitem.getProduto().getPreco()));
		    jlitematual.setText(novoitem.getProduto().getNome());
		    jftfquantidade.requestFocusInWindow();
		}catch(NullPointerException ex){
		    JOptionPane.showMessageDialog(null, "Produto inexistente", "Código inválido", JOptionPane.ERROR_MESSAGE);
		}
	    }
	}
	
    }//GEN-LAST:event_jftfcodigoKeyTyped

    private void jftfquantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftfquantidadeKeyPressed
	int key = evt.getKeyCode();
	if(key == KeyEvent.VK_ENTER){
	    try{
		int quantidade = Integer.parseInt(jftfquantidade.getText());
		if(quantidade < 1){
		    throw new NumberFormatException();
		}
		novoitem.setQuantidade(quantidade);
		novoitem.atualizarSubTotal();
		DecimalFormat df= new DecimalFormat("#.00");
		jtfsubtotal.setText("R$ " + df.format(novoitem.getSubTotal()));
		jlitematual.setText(novoitem.getProduto().getNome() + " x" + novoitem.getQuantidade());
		vtm.getVenda().adicionarItem(novoitem);
		vtm.fireTableDataChanged();
		vtm.getVenda().atualizarPrecototal();
		jttotal.setText("R$ " + df.format(vtm.getVenda().getPrecototal()));
		novoitem = new Item();
		jftfcodigo.setText(null);
		jftfquantidade.setText(null);
		jftfcodigo.requestFocusInWindow();
	    }catch(NullPointerException ex){
		jftfcodigo.requestFocusInWindow();
	    }catch(NumberFormatException ex){
		JOptionPane.showMessageDialog(null, "Insira um valor positivo", "Valor inválido", JOptionPane.ERROR_MESSAGE);
	    }
	}
    }//GEN-LAST:event_jftfquantidadeKeyPressed

    private void jbpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpesquisarActionPerformed
        TelaDeBuscaDeProdutos win = new TelaDeBuscaDeProdutos();
	win.setVisible(true);
	setEnabled(false);
	win.addWindowListener(new WindowAdapter() {
	    public void windowClosed(WindowEvent e){
		try{
		    jftfcodigo.setValue(win.getSelectedProduct().getId());
		}catch(NullPointerException ex){
		    jftfcodigo.setValue(null);
		    //JOptionPane.showMessageDialog(null, "", "Erro de código", JOptionPane.ERROR_MESSAGE);
		}
		setEnabled(true);
		jftfcodigo.requestFocusInWindow();
	    }
	});
    }//GEN-LAST:event_jbpesquisarActionPerformed

    private void jbselecionarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbselecionarclienteActionPerformed
        TelaDeBuscaDeClientes win = new TelaDeBuscaDeClientes();
	win.setVisible(true);
	setEnabled(false);
	win.addWindowListener(new WindowAdapter() {
	    public void windowClosed(WindowEvent e){
		try{
		venda.setClienteproprietario(win.getClienteselecionado());
		jlclienteselecionado.setText(venda.getCliente().getNome());
		}catch(NullPointerException ex){
		    venda.setClienteproprietario(null);
		}
		setEnabled(true);
	    }
	});
    }//GEN-LAST:event_jbselecionarclienteActionPerformed

    private void jbfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfinalizarActionPerformed
        if(venda.getClienteproprietario() != null){
	    TelaDeValor d = new TelaDeValor();
	    d.setVisible(true);
	    d.addWindowListener(new WindowAdapter() {
		public void windowClosed(WindowEvent e){
		    venda.setDinheiro(d.getValor());
		    NotaFiscal notafiscal = new NotaFiscal(venda);
		    TelaDeResumo win = new TelaDeResumo(notafiscal);
		    win.setVisible(true);
		    dispose();
		}
	    });
	}else{
	    JOptionPane.showMessageDialog(null, "Selecione um cliente antes de finalizar a compra", "Sem Cliente atribuído", JOptionPane.ERROR_MESSAGE);
	}
	
    }//GEN-LAST:event_jbfinalizarActionPerformed

    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed
	vtm.getVenda().limparItens();
	vtm.fireTableDataChanged();
    }//GEN-LAST:event_jblimparActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbfinalizar;
    private javax.swing.JButton jblimpar;
    private javax.swing.JButton jbpesquisar;
    private javax.swing.JButton jbremover;
    private javax.swing.JButton jbselecionarcliente;
    private javax.swing.JFormattedTextField jftfcodigo;
    private javax.swing.JFormattedTextField jftfquantidade;
    private javax.swing.JLabel jlcliente;
    private javax.swing.JLabel jlclienteselecionado;
    private javax.swing.JLabel jlitematual;
    private javax.swing.JPanel jpnomeproduto;
    private javax.swing.JTextField jtfsubtotal;
    private javax.swing.JTextField jtfvalorunitario;
    private javax.swing.JTable jtlistadecompras;
    private javax.swing.JTextField jttotal;
    // End of variables declaration//GEN-END:variables
}
