/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paulo
 */
public class TelaDeValor extends javax.swing.JFrame {
    private double valor;

    public double getValor() {
	return valor;
    }

    public void setValor(double valor) {
	this.valor = valor;
    }
    /**
     * Creates new form TelaDeValor
     */
    public TelaDeValor() {
	initComponents();
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlvalor = new javax.swing.JLabel();
        jftfvalorpago = new javax.swing.JFormattedTextField();
        jbpagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Finalizar");
        setAlwaysOnTop(true);
        setResizable(false);

        jlvalor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlvalor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlvalor.setText("Valor pago:");

        jftfvalorpago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jftfvalorpago.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jftfvalorpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfvalorpagoActionPerformed(evt);
            }
        });

        jbpagar.setText("Pagar");
        jbpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbpagar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftfvalorpago, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfvalorpago, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbpagar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftfvalorpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfvalorpagoActionPerformed
        jbpagar.requestFocusInWindow();
    }//GEN-LAST:event_jftfvalorpagoActionPerformed

    private void jbpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpagarActionPerformed
        DecimalFormat df = new DecimalFormat("#,#.00");
	try {
	    setValor(df.parse(jftfvalorpago.getText()).doubleValue());
	} catch (ParseException ex) {
	    Logger.getLogger(TelaDeValor.class.getName()).log(Level.SEVERE, null, ex);
	}
	dispose();
    }//GEN-LAST:event_jbpagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbpagar;
    private javax.swing.JFormattedTextField jftfvalorpago;
    private javax.swing.JLabel jlvalor;
    // End of variables declaration//GEN-END:variables
}
