
package view;

import dao.ClienteDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author paulo
 */
public class TelaDeBuscaDeClientes extends javax.swing.JFrame {
    private BuscaClienteTableModel bctm = new BuscaClienteTableModel();;
    private Cliente clienteselecionado;

    public void setClienteselecionado(Cliente clienteselecionado) {
	this.clienteselecionado = clienteselecionado;
    }

    public Cliente getClienteselecionado() {
	return clienteselecionado;
    }

    public TelaDeBuscaDeClientes() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfbuscar = new javax.swing.JTextField();
        jlbuscar = new javax.swing.JLabel();
        jbadicionar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbnovocliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Cliente");
        setResizable(false);

        jtfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarActionPerformed(evt);
            }
        });
        jtfbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfbuscarKeyPressed(evt);
            }
        });

        jlbuscar.setText("Buscar:");

        jbadicionar.setText("Adicionar");
        jbadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbadicionarActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jTable1.setModel(bctm);
        jScrollPane1.setViewportView(jTable1);

        jbnovocliente.setText("Novo");
        jbnovocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jbadicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbcancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnovocliente)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbuscar)
                    .addComponent(jbnovocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbcancelar)
                    .addComponent(jbadicionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarActionPerformed
	ClienteDAO c = new ClienteDAO();
        bctm.setClientList(c.pesquisar(jtfbuscar.getText()));
	bctm.fireTableDataChanged();
    }//GEN-LAST:event_jtfbuscarActionPerformed

    private void jtfbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarKeyPressed

        /*
        TableRowSorter<TableModel> sorter = new TableRowSorter<>((jTable1.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText()));
        jTable1.setRowSorter(sorter);
        */
    }//GEN-LAST:event_jtfbuscarKeyPressed

    private void jbadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbadicionarActionPerformed
	try{
            setClienteselecionado(bctm.getClientAtIndex(jTable1.convertRowIndexToModel(jTable1.getSelectedRow())));
        }catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Cliente não selecionado", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
	dispose();
    }//GEN-LAST:event_jbadicionarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbnovoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoclienteActionPerformed
        TelaDeCadastroDeClientes win = new TelaDeCadastroDeClientes();
	win.setVisible(true);
        setEnabled(false);
        win.addWindowListener(new WindowAdapter() {
	    @Override
	    public void windowClosed(WindowEvent e) {
		 setEnabled(true);
		 bctm.fireTableDataChanged();
            }
        });
    }//GEN-LAST:event_jbnovoclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbadicionar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbnovocliente;
    private javax.swing.JLabel jlbuscar;
    private javax.swing.JTextField jtfbuscar;
    // End of variables declaration//GEN-END:variables

}

